training01
UofT-VEEP/VEEP-Website pull request #11
Opened 2022-02-13 18:12 UTC by YuhaoGuan28

2022-02-13 19:07 UTC, Felix-Deng approved these changes
Good job, Kevin!

2022-02-21 23:41 UTC, Felix-Deng approved these changes
Good job, Kevin! The website looks good!

2022-02-22 00:42 UTC, CatherineZM requested changes

2022-02-22 00:42 UTC, CatherineZM commented on src/HomePage.js
> +import { Container } from 'react-bootstrap';
This can be combined into `import { Card, Accordion, Navbar, Nav, Container} from 'react-bootstrap';`

2022-02-22 00:42 UTC, CatherineZM commented on src/HomePage.js
> +            <Nav.Link href="#pricing">About Us</Nav.Link>
Even though we don't have pages to jump to right now. It's always good to change the href into corresponding name

2022-02-22 01:07 UTC, CatherineZM commented
@Felix-Deng @iiiizuo I forgot to close this PR before so Kevin's week 2 got pushed onto this PR. Can you take a look when you get a chance and once you approved, you can close this PR

2022-03-05 15:19 UTC, Felix-Deng approved these changes
Good job, Kevin! Your website looks good!

2022-03-08 20:44 UTC, closed without merging